CREATE TABLE `reg_failure_type` (
	`CODE` VARCHAR(16) NOT NULL,
	`DESCRIPTION` VARCHAR(64) NULL DEFAULT NULL,
	`STATUS` VARCHAR(16) NULL DEFAULT NULL COLLATE 'latin1_swedish_ci' ,
	`LASTUPDATEDUSER` VARCHAR(64) NULL DEFAULT NULL,
	`LASTUPDATEDTIME` DATETIME NULL DEFAULT current_timestamp(),
	`CREATEDTIME` DATETIME NULL DEFAULT current_timestamp(),
	`CREATEDUSER` VARCHAR(64) NULL DEFAULT NULL,
	PRIMARY KEY (`CODE`) ,
	CONSTRAINT `reg_failure_type_FK` FOREIGN KEY (`STATUS`) REFERENCES `status` (`STATUSCODE`) ON UPDATE RESTRICT ON DELETE RESTRICT
);

COMMIT;

CREATE TABLE `reg_failure_area` (
	`CODE` VARCHAR(16) NOT NULL,
	`DESCRIPTION` VARCHAR(64) NULL DEFAULT NULL,
	`STATUS` VARCHAR(16) NULL DEFAULT NULL COLLATE 'latin1_swedish_ci' ,
	`LASTUPDATEDUSER` VARCHAR(64) NULL DEFAULT NULL,
	`LASTUPDATEDTIME` DATETIME NULL DEFAULT current_timestamp(),
	`CREATEDTIME` DATETIME NULL DEFAULT current_timestamp(),
	`CREATEDUSER` VARCHAR(64) NULL DEFAULT NULL,
	PRIMARY KEY (`CODE`) ,
	CONSTRAINT `reg_failure_area_FK` FOREIGN KEY (`STATUS`) REFERENCES `status` (`STATUSCODE`) ON UPDATE RESTRICT ON DELETE RESTRICT
);

COMMIT;

CREATE TABLE `reg_failure_type_repair` (
	`CODE` VARCHAR(16) NOT NULL,
	`DESCRIPTION` VARCHAR(64) NULL DEFAULT NULL,
	`STATUS` VARCHAR(16) NULL DEFAULT NULL COLLATE 'latin1_swedish_ci' ,
	`LASTUPDATEDUSER` VARCHAR(64) NULL DEFAULT NULL,
	`LASTUPDATEDTIME` DATETIME NULL DEFAULT current_timestamp(),
	`CREATEDTIME` DATETIME NULL DEFAULT current_timestamp(),
	`CREATEDUSER` VARCHAR(64) NULL DEFAULT NULL,
	PRIMARY KEY (`CODE`) ,
	CONSTRAINT `reg_failure_type_repair_FK` FOREIGN KEY (`STATUS`) REFERENCES `status` (`STATUSCODE`) ON UPDATE RESTRICT ON DELETE RESTRICT
);

COMMIT;


INSERT INTO `reg_failure_area` (`CODE`, `DESCRIPTION`, `STATUS`, `LASTUPDATEDUSER`, `LASTUPDATEDTIME`, `CREATEDTIME`, `CREATEDUSER`) VALUES ('1', 'R F AREA 1', 'ACT', 'admin', '2022-08-31 17:07:16', '2022-08-31 17:07:16', 'admin');
INSERT INTO `reg_failure_area` (`CODE`, `DESCRIPTION`, `STATUS`, `LASTUPDATEDUSER`, `LASTUPDATEDTIME`, `CREATEDTIME`, `CREATEDUSER`) VALUES ('2', 'R F AREA 2', 'ACT', 'admin', '2022-08-31 17:07:16', '2022-08-31 17:07:16', 'admin');
INSERT INTO `reg_failure_area` (`CODE`, `DESCRIPTION`, `STATUS`, `LASTUPDATEDUSER`, `LASTUPDATEDTIME`, `CREATEDTIME`, `CREATEDUSER`) VALUES ('3', 'R F AREA 3', 'ACT', 'admin', '2022-08-31 17:07:16', '2022-08-31 17:07:16', 'admin');


INSERT INTO `reg_failure_type` (`CODE`, `DESCRIPTION`, `STATUS`, `LASTUPDATEDUSER`, `LASTUPDATEDTIME`, `CREATEDTIME`, `CREATEDUSER`) VALUES ('1', 'F TYPE 1', 'ACT', 'admin', '2022-08-31 17:05:03', '2022-08-31 17:05:04', 'admin');
INSERT INTO `reg_failure_type` (`CODE`, `DESCRIPTION`, `STATUS`, `LASTUPDATEDUSER`, `LASTUPDATEDTIME`, `CREATEDTIME`, `CREATEDUSER`) VALUES ('2', 'F TYPE 2', 'ACT', 'admin', '2022-08-31 17:05:03', '2022-08-31 17:05:04', 'admin');
INSERT INTO `reg_failure_type` (`CODE`, `DESCRIPTION`, `STATUS`, `LASTUPDATEDUSER`, `LASTUPDATEDTIME`, `CREATEDTIME`, `CREATEDUSER`) VALUES ('3', 'F TYPE 3', 'ACT', 'admin', '2022-08-31 17:05:03', '2022-08-31 17:05:04', 'admin');

INSERT INTO `reg_failure_type_repair` (`CODE`, `DESCRIPTION`, `STATUS`, `LASTUPDATEDUSER`, `LASTUPDATEDTIME`, `CREATEDTIME`, `CREATEDUSER`) VALUES ('1', 'F R TYPE 1', 'ACT', 'admin', '2022-08-31 17:06:24', '2022-08-31 17:06:24', 'admin');
INSERT INTO `reg_failure_type_repair` (`CODE`, `DESCRIPTION`, `STATUS`, `LASTUPDATEDUSER`, `LASTUPDATEDTIME`, `CREATEDTIME`, `CREATEDUSER`) VALUES ('2', 'F R TYPE 2', 'ACT', 'admin', '2022-08-31 17:06:24', '2022-08-31 17:06:24', 'admin');
INSERT INTO `reg_failure_type_repair` (`CODE`, `DESCRIPTION`, `STATUS`, `LASTUPDATEDUSER`, `LASTUPDATEDTIME`, `CREATEDTIME`, `CREATEDUSER`) VALUES ('3', 'F R TYPE 3', 'ACT', 'admin', '2022-08-31 17:06:24', '2022-08-31 17:06:24', 'admin');

COMMIT;